name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use docker
      uses: actions/setup-node@v1
    - name: Build image
      run: docker build --file Dockerfile --tag maciekmm/pypy-scientific:${GITHUB_REF##*/} .
    - name: Login to Docker Hub
      run: docker login --username maciekmm --password "${DOCKER_HUB_TOKEN}"
    - name: Push image
      run : docker push maciekmm/pypy-scientific:${GITHUB_REF##*/}
